# ===============================
# APPLICATION CORE CONFIG
# ===============================
spring.application.name=HospitalManagementSystem
server.port=8899

# ===============================
# DATABASE CONFIGURATION (PostgreSQL)
# ===============================
jwt.secret=l7DxbhGyTwZLoOrhgxoxtGYlwl9fIax6idcSD8U8t6SNzZ4mTn+prF8GCxgeAGBorlHcivLQ6lMVBUikO2+3CQ==
app.auth.enforce-2fa=true
# Enable return code for demo purposes so user isn't locked out
app.auth.return-2fa-code=false
app.demo-data.enabled=true
app.location.import-on-startup=false
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_db
spring.datasource.username=postgres
spring.datasource.password=ap
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.sql.init.mode=never

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# ===============================
# MAIL CONFIGURATION
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=apjr.nzendong@gmail.com
spring.mail.password=urtvawbtwbemysop
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# FILE GENERATION (PDF PATH)
# ===============================
hospital.billing.pdf.dir=./bills/

# ===============================
# LOGGING CONFIG
# ===============================
logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.file.name=logs/hospital.log
